// AUTO-GENERATED FILE (runtime)
// Generated by IpcRouter
import type { z } from 'zod'
import type * as Mod_auth from '../main/routes/auth'
import type * as Mod_macaddress from '../main/routes/macaddress'
import type * as Mod_query_encounter from '../main/routes/query/encounter'
import type * as Mod_query_expense from '../main/routes/query/expense'
import type * as Mod_query_expenseHead from '../main/routes/query/expenseHead'
import type * as Mod_query_patient from '../main/routes/query/patient'
import type * as Mod_user from '../main/routes/user'
type Invoke<Args = unknown, Result = unknown> = (args?: Args) => Promise<Result>
type InferArgs<M, K extends string> = M extends { schemas: Record<string, any> }
  ? K extends keyof M['schemas']
    ? M['schemas'][K] extends { args: infer A extends z.ZodTypeAny }
      ? z.input<A>
      : unknown
    : unknown
  : M extends { schemas: infer S }
  ? K extends keyof S
    ? S[K] extends { args: infer A extends z.ZodTypeAny }
      ? z.input<A>
      : unknown
    : unknown
  : M extends { argsSchema: infer A extends z.ZodTypeAny }
  ? z.input<A>
  : unknown
type InferResult<M, K extends string> = M extends { schemas: Record<string, any> }
  ? K extends keyof M['schemas']
    ? M['schemas'][K] extends { result: infer R extends z.ZodTypeAny }
      ? z.output<R>
      : unknown
    : unknown
  : M extends { schemas: infer S }
  ? K extends keyof S
    ? S[K] extends { result: infer R extends z.ZodTypeAny }
      ? z.output<R>
      : unknown
    : unknown
  : M extends { resultSchema: infer R extends z.ZodTypeAny }
  ? z.output<R>
  : unknown
type Args_Mod_auth_getSession = InferArgs<typeof Mod_auth, 'getSession'>
type Result_Mod_auth_getSession = InferResult<typeof Mod_auth, 'getSession'>
type Args_Mod_auth_login = InferArgs<typeof Mod_auth, 'login'>
type Result_Mod_auth_login = InferResult<typeof Mod_auth, 'login'>
type Args_Mod_auth_logout = InferArgs<typeof Mod_auth, 'logout'>
type Result_Mod_auth_logout = InferResult<typeof Mod_auth, 'logout'>
type Args_Mod_auth_status = InferArgs<typeof Mod_auth, 'status'>
type Result_Mod_auth_status = InferResult<typeof Mod_auth, 'status'>
type Args_Mod_macaddress_getPrimaryMacAddress = InferArgs<typeof Mod_macaddress, 'getPrimaryMacAddress'>
type Result_Mod_macaddress_getPrimaryMacAddress = InferResult<typeof Mod_macaddress, 'getPrimaryMacAddress'>
type Args_Mod_query_encounter_create = InferArgs<typeof Mod_query_encounter, 'create'>
type Result_Mod_query_encounter_create = InferResult<typeof Mod_query_encounter, 'create'>
type Args_Mod_query_encounter_deleteById = InferArgs<typeof Mod_query_encounter, 'deleteById'>
type Result_Mod_query_encounter_deleteById = InferResult<typeof Mod_query_encounter, 'deleteById'>
type Args_Mod_query_encounter_getById = InferArgs<typeof Mod_query_encounter, 'getById'>
type Result_Mod_query_encounter_getById = InferResult<typeof Mod_query_encounter, 'getById'>
type Args_Mod_query_encounter_list = InferArgs<typeof Mod_query_encounter, 'list'>
type Result_Mod_query_encounter_list = InferResult<typeof Mod_query_encounter, 'list'>
type Args_Mod_query_encounter_update = InferArgs<typeof Mod_query_encounter, 'update'>
type Result_Mod_query_encounter_update = InferResult<typeof Mod_query_encounter, 'update'>
type Args_Mod_query_expense_create = InferArgs<typeof Mod_query_expense, 'create'>
type Result_Mod_query_expense_create = InferResult<typeof Mod_query_expense, 'create'>
type Args_Mod_query_expense_deleteById = InferArgs<typeof Mod_query_expense, 'deleteById'>
type Result_Mod_query_expense_deleteById = InferResult<typeof Mod_query_expense, 'deleteById'>
type Args_Mod_query_expense_list = InferArgs<typeof Mod_query_expense, 'list'>
type Result_Mod_query_expense_list = InferResult<typeof Mod_query_expense, 'list'>
type Args_Mod_query_expense_seed = InferArgs<typeof Mod_query_expense, 'seed'>
type Result_Mod_query_expense_seed = InferResult<typeof Mod_query_expense, 'seed'>
type Args_Mod_query_expense_update = InferArgs<typeof Mod_query_expense, 'update'>
type Result_Mod_query_expense_update = InferResult<typeof Mod_query_expense, 'update'>
type Args_Mod_query_expenseHead_list = InferArgs<typeof Mod_query_expenseHead, 'list'>
type Result_Mod_query_expenseHead_list = InferResult<typeof Mod_query_expenseHead, 'list'>
type Args_Mod_query_expenseHead_seed = InferArgs<typeof Mod_query_expenseHead, 'seed'>
type Result_Mod_query_expenseHead_seed = InferResult<typeof Mod_query_expenseHead, 'seed'>
type Args_Mod_query_patient_create = InferArgs<typeof Mod_query_patient, 'create'>
type Result_Mod_query_patient_create = InferResult<typeof Mod_query_patient, 'create'>
type Args_Mod_query_patient_deleteById = InferArgs<typeof Mod_query_patient, 'deleteById'>
type Result_Mod_query_patient_deleteById = InferResult<typeof Mod_query_patient, 'deleteById'>
type Args_Mod_query_patient_getById = InferArgs<typeof Mod_query_patient, 'getById'>
type Result_Mod_query_patient_getById = InferResult<typeof Mod_query_patient, 'getById'>
type Args_Mod_query_patient_list = InferArgs<typeof Mod_query_patient, 'list'>
type Result_Mod_query_patient_list = InferResult<typeof Mod_query_patient, 'list'>
type Args_Mod_query_patient_update = InferArgs<typeof Mod_query_patient, 'update'>
type Result_Mod_query_patient_update = InferResult<typeof Mod_query_patient, 'update'>
type Args_Mod_user_create = InferArgs<typeof Mod_user, 'create'>
type Result_Mod_user_create = InferResult<typeof Mod_user, 'create'>
type Args_Mod_user_get = InferArgs<typeof Mod_user, 'get'>
type Result_Mod_user_get = InferResult<typeof Mod_user, 'get'>
type Args_Mod_user_list = InferArgs<typeof Mod_user, 'list'>
type Result_Mod_user_list = InferResult<typeof Mod_user, 'list'>
declare global {
  interface Window {
    api: {
      auth: {
        getSession: Invoke<Args_Mod_auth_getSession, Result_Mod_auth_getSession>
        login: Invoke<Args_Mod_auth_login, Result_Mod_auth_login>
        logout: Invoke<Args_Mod_auth_logout, Result_Mod_auth_logout>
        status: Invoke<Args_Mod_auth_status, Result_Mod_auth_status>
      }
      macaddress: {
        getPrimaryMacAddress: Invoke<Args_Mod_macaddress_getPrimaryMacAddress, Result_Mod_macaddress_getPrimaryMacAddress>
      }
      query: {
        encounter: {
          create: Invoke<Args_Mod_query_encounter_create, Result_Mod_query_encounter_create>
          deleteById: Invoke<Args_Mod_query_encounter_deleteById, Result_Mod_query_encounter_deleteById>
          getById: Invoke<Args_Mod_query_encounter_getById, Result_Mod_query_encounter_getById>
          list: Invoke<Args_Mod_query_encounter_list, Result_Mod_query_encounter_list>
          update: Invoke<Args_Mod_query_encounter_update, Result_Mod_query_encounter_update>
        }
        expense: {
          create: Invoke<Args_Mod_query_expense_create, Result_Mod_query_expense_create>
          deleteById: Invoke<Args_Mod_query_expense_deleteById, Result_Mod_query_expense_deleteById>
          list: Invoke<Args_Mod_query_expense_list, Result_Mod_query_expense_list>
          seed: Invoke<Args_Mod_query_expense_seed, Result_Mod_query_expense_seed>
          update: Invoke<Args_Mod_query_expense_update, Result_Mod_query_expense_update>
        }
        expenseHead: {
          list: Invoke<Args_Mod_query_expenseHead_list, Result_Mod_query_expenseHead_list>
          seed: Invoke<Args_Mod_query_expenseHead_seed, Result_Mod_query_expenseHead_seed>
        }
        patient: {
          create: Invoke<Args_Mod_query_patient_create, Result_Mod_query_patient_create>
          deleteById: Invoke<Args_Mod_query_patient_deleteById, Result_Mod_query_patient_deleteById>
          getById: Invoke<Args_Mod_query_patient_getById, Result_Mod_query_patient_getById>
          list: Invoke<Args_Mod_query_patient_list, Result_Mod_query_patient_list>
          update: Invoke<Args_Mod_query_patient_update, Result_Mod_query_patient_update>
        }
      }
      user: {
        create: Invoke<Args_Mod_user_create, Result_Mod_user_create>
        get: Invoke<Args_Mod_user_get, Result_Mod_user_get>
        list: Invoke<Args_Mod_user_list, Result_Mod_user_list>
      }
    }
  }
}
export {}
